---
- block:
    - include: init.yml

- block:
    - include: disable_policy.yml
  when: cf_disable_stack_policy

- block:
    - include: generator.yml
    - include: s3.yml
      when: cf_upload_s3
    - include: cloudformation.yml
  rescue:
    - name: capture failure
      set_fact:
        cf_failure: "true"
  always:
    - include: enable_policy.yml
      when: cf_disable_stack_policy
    - fail: msg="The playbook encountered an error"
      when: cf_failure | default(False) | bool
  when: not cf_delete_stack

- block:
    - include: delete.yml
  when: cf_delete_stack